In [ ]:
pwd

'/content'

In [1]:
%pushd /content
import numpy as np
import pandas as pd
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 25
pd.options.display.max_columns = 20
pd.options.display.max_colwidth = 82
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

/content


In [ ]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [ ]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [ ]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [ ]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [ ]:
float_data = pd.Series([1, 2, None], dtype='float64')
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [ ]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [ ]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [ ]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [ ]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
data[4] = np.nan
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [ ]:
data.dropna(axis="columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df

0         1         2
0 -0.204708  0.478943 -0.519439
1 -0.555730  1.965781  1.393406
2  0.092908  0.281746  0.769023
3  1.246435  1.007189 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [ ]:
df.iloc[:4, 1] = np.nan
df

0         1         2
0 -0.204708       NaN -0.519439
1 -0.555730       NaN  1.393406
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [ ]:
df.dropna()

0         1         2
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [ ]:
df.dropna(thresh=2)

0         1         2
0 -0.204708       NaN -0.519439
1 -0.555730       NaN  1.393406
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

- `dropna`: To metoda, która służy do usuwania brakujących danych (NaN) z DataFrame.
- `thresh=3`: Parametr `thresh` określa minimalną liczbę niepustych wartości, które musi zawierać wiersz, aby został zachowany. W tym przypadku, wiersze muszą mieć co najmniej 2 niepuste wartości, aby pozostały w DataFrame.

In [ ]:
df.dropna(thresh=3)

0         1         2
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [ ]:
df

0         1         2
0 -0.204708       NaN -0.519439
1 -0.555730       NaN  1.393406
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [ ]:
df.fillna(0)

0         1         2
0 -0.204708  0.000000 -0.519439
1 -0.555730  0.000000  1.393406
2  0.092908  0.000000  0.769023
3  1.246435  0.000000 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [ ]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.204708  0.500000 -0.519439
1 -0.555730  0.500000  1.393406
2  0.092908  0.500000  0.769023
3  1.246435  0.500000 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [ ]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df

0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772  0.000940  1.343810
3 -0.713544 -0.831154 -2.370232
4 -1.860761 -0.860757  0.560145
5 -1.265934  0.119827 -1.063512

In [ ]:
df.iloc[2:, 1] = np.nan
df

0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772       NaN  1.343810
3 -0.713544       NaN -2.370232
4 -1.860761       NaN  0.560145
5 -1.265934       NaN -1.063512

In [ ]:
df.iloc[4:, 2] = np.nan
df

0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772       NaN  1.343810
3 -0.713544       NaN -2.370232
4 -1.860761       NaN       NaN
5 -1.265934       NaN       NaN

In [ ]:
df

0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772       NaN  1.343810
3 -0.713544       NaN -2.370232
4 -1.860761       NaN       NaN
5 -1.265934       NaN       NaN

- Metoda fillna(method="ffill") w pandas wypełnia brakujące wartości (NaN) używając wartości z poprzedniego wiersza

In [ ]:
df.fillna(method="ffill")

<ipython-input-44-5a0d178a1f3e>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")


0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772  0.124121  1.343810
3 -0.713544  0.124121 -2.370232
4 -1.860761  0.124121 -2.370232
5 -1.265934  0.124121 -2.370232

In [ ]:
df.fillna(method="ffill", limit=2)

<ipython-input-45-f081c1453b62>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", limit=2)


0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772  0.124121  1.343810
3 -0.713544  0.124121 -2.370232
4 -1.860761       NaN -2.370232
5 -1.265934       NaN -2.370232

In [ ]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [ ]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [ ]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [ ]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [ ]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [ ]:
data["v1"] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

- `drop_duplicates`: Metoda ta identyfikuje i usuwa wiersze, które mają identyczne wartości w określonym zbiorze kolumn.
- `subset="k1"`: Parametr `subset` pozwala określić, które kolumny będą brane pod uwagę przy identyfikacji duplikatów. W tym przypadku tylko kolumna `"k1"` jest używana do tej analizy.

In [ ]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

- `drop_duplicates`: Metoda ta identyfikuje i usuwa wiersze, które mają identyczne wartości w określonym zbiorze kolumn.
- `"k1", "k2"`: Parametr ten określa kolumny, na podstawie których będą identyfikowane duplikaty. W tym przypadku zarówno kolumna `"k1"`, jak i kolumna `"k2"` są brane pod uwagę.
- `keep="last"`: Ten parametr określa, który z duplikatów ma być zachowany. Ustawienie `keep="last"` oznacza, że ostatni wystąpienie duplikatu zostanie zachowane, a wcześniejsze zostaną usunięte.

In [ ]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [ ]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [ ]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [ ]:
data["animal"] = data["food"].map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [ ]:
def get_animal(x):
    return meat_to_animal[x]

data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [ ]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [ ]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [ ]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [ ]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [ ]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [ ]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [17]:
data.index

Index(['Ohio', 'Colorado', 'New York'], dtype='object')

In [16]:
def transform(x):
    return x[:4].upper()

data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [18]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [20]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [21]:
data.rename(index={"OHIO": "INDIANA"},
            columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [22]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

- Funkcja `pd.cut()` z biblioteki Pandas służy do dzielenia danych na kategorie na podstawie określonych granic.

In [23]:
bins = [18, 25, 35, 60, 100]
age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

- `age_categories` to wynik działania funkcji `pd.cut()`, która dzieli dane na kategorie na podstawie zdefiniowanych binów.
- Atrybut `.codes` zwraca numeryczne kody przypisane do każdej kategorii.

In [24]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

- Atrybut `.categories` zwraca listę unikalnych kategorii, które zostały utworzone podczas kategoryzacji danych za pomocą `pd.cut()`. W przypadku, gdy wcześniej zdefiniowano przedziały wiekowe, ten atrybut pokaże te przedziały.

In [25]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [26]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [27]:
pd.value_counts(age_categories)

<ipython-input-27-eed211f460ce>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [28]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [29]:
# [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [30]:
age_categories2 = pd.cut(ages, bins, labels=group_names)
pd.value_counts(age_categories2)

<ipython-input-30-6030ceab4b72>:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories2)


Youth         5
YoungAdult    3
MiddleAged    3
Senior        1
Name: count, dtype: int64

In [31]:
data = np.random.uniform(size=20)
data

array([0.9296, 0.3164, 0.1839, 0.2046, 0.5677, 0.5955, 0.9645, 0.6532,
       0.7489, 0.6536, 0.7477, 0.9613, 0.0084, 0.1064, 0.2987, 0.6564,
       0.8098, 0.8722, 0.9646, 0.7237])

In [32]:
pd.cut(data, 4, precision=2)

[(0.73, 0.96], (0.25, 0.49], (0.0074, 0.25], (0.0074, 0.25], (0.49, 0.73], ..., (0.49, 0.73], (0.73, 0.96], (0.73, 0.96], (0.73, 0.96], (0.49, 0.73]]
Length: 20
Categories (4, interval[float64, right]): [(0.0074, 0.25] < (0.25, 0.49] < (0.49, 0.73] <
                                           (0.73, 0.96]]

- `bins`: Wartość `4` oznacza, że dane zostaną podzielone na cztery równe przedziały. Funkcja automatycznie obliczy granice tych przedziałów na podstawie wartości w `data`.
- `precision`: Ustalona na `2`, co oznacza, że etykiety przedziałów będą zaokrąglone do dwóch miejsc po przecinku.

In [33]:
# [(0.0074, 0.25] < (0.25, 0.49] < (0.49, 0.73] < (0.73, 0.96]]

data_bin = pd.cut(data, 4, precision=2)
pd.value_counts(data_bin)

<ipython-input-33-d776c78b6252>:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(data_bin)


(0.73, 0.96]      8
(0.49, 0.73]      6
(0.0074, 0.25]    4
(0.25, 0.49]      2
Name: count, dtype: int64

In [34]:
data = np.random.standard_normal(1000)
data

array([ 1.3529,  0.8864, -2.0016, -0.3718,  1.669 , -0.4386, -0.5397,
        0.477 ,  3.2489, -1.0212, -0.5771,  0.1241,  0.3026,  0.5238,
        0.0009,  1.3438, -0.7135, -0.8312, -2.3702, -1.8608, -0.8608,
        0.5601, -1.2659,  0.1198, -1.0635,  0.3329, -2.3594, -0.1995,
       -1.542 , -0.9707, -1.307 ,  0.2863,  0.378 , -0.7539,  0.3313,
        1.3497,  0.0699,  0.2467, -0.0119,  1.0048,  1.3272, -0.9193,
       -1.5491,  0.0222,  0.7584, -0.6605,  0.8626, -0.01  ,  0.05  ,
        0.6702,  0.853 , -0.9559, -0.0235, -2.3042, -0.6525, -1.2183,
       -1.3326,  1.0746,  0.7236,  0.69  ,  1.0015, -0.5031, -0.6223,
       -0.9212, -0.7262,  0.2229,  0.0513, -1.1577,  0.8167,  0.4336,
        1.0107,  1.8249, -0.9975,  0.8506, -0.1316,  0.9124,  0.1882,
        2.1695, -0.1149,  2.0037,  0.0296,  0.7953,  0.1181, -0.7485,
        0.585 ,  0.1527, -1.5657, -0.5625, -0.0327, -0.929 , -0.4826,
       -0.0363,  1.0954,  0.9809, -0.5895,  1.5817, -0.5287,  0.457 ,
        0.93  , -1.5

- Funkcja `pd.qcut()` w bibliotece Pandas jest używana do dzielenia danych na kwartyle, co pozwala na segmentację danych na równe części.

In [35]:
# [(-2.96, -0.69] < (-0.69, -0.017] < (-0.017, 0.63] < (0.63, 3.93]]

quartiles = pd.qcut(data, 4, precision=2)
quartiles

[(0.63, 3.93], (0.63, 3.93], (-2.96, -0.69], (-0.69, -0.017], (0.63, 3.93], ..., (-0.017, 0.63], (0.63, 3.93], (-0.69, -0.017], (-0.69, -0.017], (-0.017, 0.63]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.96, -0.69] < (-0.69, -0.017] < (-0.017, 0.63] <
                                           (0.63, 3.93]]

In [36]:
pd.value_counts(quartiles)

<ipython-input-36-e680040d00da>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)


(-2.96, -0.69]     250
(-0.69, -0.017]    250
(-0.017, 0.63]     250
(0.63, 3.93]       250
Name: count, dtype: int64

In [37]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-2.9499999999999997, -1.191]    100
(-1.191, -0.0171]                400
(-0.0171, 1.297]                 400
(1.297, 3.928]                   100
Name: count, dtype: int64

In [39]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data

0         1         2         3
0    0.323886 -1.683325  0.526860  1.858791
1   -0.548419 -0.279397 -0.021299 -0.287990
2    0.089175  0.522858  0.572796 -1.760372
3    1.128179  1.568606 -0.342277 -0.009813
4    0.053072 -0.041943 -1.694312 -0.362381
..        ...       ...       ...       ...
995 -1.029444  2.238196 -0.928520 -0.587842
996  1.429361 -2.173409  0.349901  0.863522
997  0.511796  1.761981 -0.681278  0.591952
998  0.490944 -0.699940 -0.587111  1.480221
999 -0.125103 -1.033043  2.445125 -0.021998

[1000 rows x 4 columns]

In [40]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.021425    -0.005165    -0.055670     0.044107
std       1.008404     0.995532     0.994484     0.996884
min      -3.184377    -3.745356    -3.428254    -3.645860
25%      -0.628122    -0.699383    -0.747478    -0.599807
50%      -0.016127    -0.029924    -0.091364     0.043663
75%       0.690847     0.694459     0.620197     0.740562
max       3.525865     2.735527     3.366626     2.653656

In [41]:
col = data[2]
col

0      0.526860
1     -0.021299
2      0.572796
3     -0.342277
4     -1.694312
         ...   
995   -0.928520
996    0.349901
997   -0.681278
998   -0.587111
999    2.445125
Name: 2, Length: 1000, dtype: float64

In [42]:
col[col.abs() > 3]

269   -3.428254
646    3.366626
Name: 2, dtype: float64

- Metoda `any()` sprawdza, czy w każdym wierszu (czyli wzdłuż kolumn) istnieje przynajmniej jedna wartość `True`. Ustawienie `axis="columns"` oznacza, że sprawdzamy wiersze, a nie kolumny. W wyniku tego otrzymujemy serię wartości logicznych, gdzie `True` oznacza, że przynajmniej jedna wartość w danym wierszu przekracza 3 (w wartościach bezwzględnych).

In [44]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
52  -0.025907 -3.399312 -0.974657 -0.685312
71   3.260383  0.963301  1.201206 -1.852001
147 -0.196713 -3.745356 -1.520113 -0.346839
246 -3.056990  1.918403 -0.578828  1.847446
269  0.326045  0.425384 -3.428254 -0.296336
333 -3.184377  1.369891 -1.074833 -0.089937
554  0.208011 -0.150923 -0.362528 -3.548824
646  0.193299  1.397822  3.366626 -2.372214
793  3.525865  0.283070  0.544635  0.462204
813 -0.450721 -0.080332  0.599947 -3.645860

- Funkcja `np.sign()` zwraca znak każdej wartości w DataFrame: `-1` dla wartości ujemnych, `0` dla zera i `1` dla wartości dodatnich. Dzięki temu można zachować oryginalny znak wartości.
- `np.sign(data) * 3` To wyrażenie mnoży wynik funkcji `np.sign(data)` przez 3, co daje wartość 3 lub -3 w zależności od znaku oryginalnej wartości.

In [52]:
data = data[data.abs() > 3] = np.sign(data) * 3
data.describe()

0           1            2            3
count  1000.000000  1000.00000  1000.000000  1000.000000
mean     -0.048000    -0.09000    -0.168000     0.132000
std       3.001117     3.00015     2.996791     2.998594
min      -3.000000    -3.00000    -3.000000    -3.000000
25%      -3.000000    -3.00000    -3.000000    -3.000000
50%      -3.000000    -3.00000    -3.000000     3.000000
75%       3.000000     3.00000     3.000000     3.000000
max       3.000000     3.00000     3.000000     3.000000

In [51]:
data = data[data.abs() > 3] = np.sign(data) * 3
data

0    1    2    3
0    3.0 -3.0  3.0  3.0
1   -3.0 -3.0 -3.0 -3.0
2    3.0  3.0  3.0 -3.0
3    3.0  3.0 -3.0 -3.0
4    3.0 -3.0 -3.0 -3.0
..   ...  ...  ...  ...
995 -3.0  3.0 -3.0 -3.0
996  3.0 -3.0  3.0  3.0
997  3.0  3.0 -3.0  3.0
998  3.0 -3.0 -3.0  3.0
999 -3.0 -3.0  3.0 -3.0

[1000 rows x 4 columns]

In [53]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0  1.0  1.0
1 -1.0 -1.0 -1.0 -1.0
2  1.0  1.0  1.0 -1.0
3  1.0  1.0 -1.0 -1.0
4  1.0 -1.0 -1.0 -1.0

- 	`np.arange(5 * 7)`: Funkcja `np.arange()` generuje jednowymiarową tablicę wartości całkowitych od 0 do 34 (łącznie 35 wartości), ponieważ `5 * 7` równa się 35.

- `.reshape((5, 7))`: Metoda `reshape()` przekształca jednowymiarową tablicę w tablicę dwuwymiarową o wymiarach 5 wierszy i 7 kolumn.

In [54]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

- Funkcja `np.random.permutation(5)` w bibliotece NumPy generuje losową permutację liczb całkowitych od 0 do 4.

In [58]:
sampler = np.random.permutation(5)
sampler

array([0, 2, 1, 3, 4])

- `take()` pozwala na wybieranie wierszy (lub kolumn) z DataFrame na podstawie ich pozycji, a nie wartości w indeksie. Oznacza to, że można wybrać elementy według ich miejsca w DataFrame.

In [59]:
df.take(sampler)

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [60]:
df.iloc[sampler]

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [61]:
column_sampler = np.random.permutation(7)
column_sampler

array([2, 6, 4, 1, 3, 5, 0])

In [62]:
df.take(column_sampler, axis="columns")

2   6   4   1   3   5   0
0   2   6   4   1   3   5   0
1   9  13  11   8  10  12   7
2  16  20  18  15  17  19  14
3  23  27  25  22  24  26  21
4  30  34  32  29  31  33  28

In [63]:
df.sample(n=3)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13

In [64]:
choices = pd.Series([5, 7, -1, 6, 4])
choices

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [65]:
choices.sample(n=10, replace=True)

0    5
3    6
2   -1
3    6
3    6
0    5
1    7
3    6
4    4
0    5
dtype: int64

In [66]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

- `get_dummies()` przekształca kolumny kategoryczne w DataFrame na wiele kolumn binarnych, gdzie każda kolumna reprezentuje jedną kategorię. Wartości w tych kolumnach są 0 lub 1, wskazując, czy dany wiersz należy do danej kategorii.

In [67]:
pd.get_dummies(df["key"])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

- Kod przedstawiony powyżej ilustruje, jak konwertować zmienne kategoryczne na zmienne binarne i jak je integrować z innymi danymi w DataFrame.

In [68]:
dummies = pd.get_dummies(df["key"], prefix="key")
df_with_dummy = df[["data1"]].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

- `engine="python"`: Używa silnika Pythona do parsowania pliku, co jest konieczne przy używaniu niestandardowych separatorów.

In [2]:
mnames = ["movie_id", "title", "genres"]

movies = pd.read_table("/content/movies.dat", sep="::",
                       header=None, names=mnames, engine="python")
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

- `.str.get_dummies("|")`: Metoda `get_dummies()` dla obiektów typu string przekształca tekst w kolumnie na zmienne binarne. Separator `|` informuje funkcję, że różne gatunki są oddzielone tym znakiem.

- `.iloc:10, :6`: Użycie `.iloc` pozwala na wybór pierwszych 10 wierszy oraz pierwszych 6 kolumn z DataFrame `dummies`. Jest to przydatne do przeglądania wyników bez konieczności wyświetlania całego DataFrame.

In [3]:
dummies = movies["genres"].str.get_dummies("|")
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

- Funkcja `join()` łączy dwa DataFrame na podstawie indeksów. W tym przypadku łączy oryginalny DataFrame `movies` z nowym DataFrame, który zawiera zmienne binarne dla gatunków.

In [4]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western                                  0
Name: 0, dtype: object

- Funkcja `uniform()` generuje losowe liczby zmiennoprzecinkowe z rozkładu jednostajnego w przedziale [0, 1). Parametr `size=10` oznacza, że chcemy wygenerować 10 takich wartości.

In [5]:
np.random.seed(12345)
values = np.random.uniform(size=10)
values

array([0.9296, 0.3164, 0.1839, 0.2046, 0.5677, 0.5955, 0.9645, 0.6532,
       0.7489, 0.6536])

In [6]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

- Pandas konwertuje wszystkie liczby na typ `float64`, ponieważ typ `None` wymaga użycia zmiennoprzecinkowego do reprezentacji wartości brakujących (NaN). Dlatego wszystkie liczby są przedstawiane jako liczby zmiennoprzecinkowe (`1.0`, `2.0`, `3.0`)

In [7]:
s = pd.Series([1, 2, 3, None])
s
s.dtype

dtype('float64')

In [11]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())
print(s)
print(s.isna())
print(s.dtype)

0       1
1       2
2       3
3    <NA>
dtype: Int64
0    False
1    False
2    False
3     True
dtype: bool
Int64


In [12]:
s[3]

<NA>

In [13]:
type(s[3])

pandas._libs.missing.NAType

In [14]:
s[3] is pd.NA

True

In [15]:
s = pd.Series([1, 2, 3, None], dtype="Int64")
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [17]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [18]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                   "C": [False, None, False, True]})
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [19]:
df["A"] = df["A"].astype("Int64")
df["A"]

0       1
1       2
2    <NA>
3       4
Name: A, dtype: Int64

In [20]:
df["B"] = df["B"].astype("string")
df["B"]

0      one
1      two
2    three
3     <NA>
Name: B, dtype: string

In [21]:
df["C"] = df["C"].astype("boolean")
df["C"]

0    False
1     <NA>
2    False
3     True
Name: C, dtype: boolean

In [22]:
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

In [23]:
val = "a,b,  guido"
val.split(",")

['a', 'b', '  guido']

In [24]:
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [25]:
first, second, third = pieces
first + "::" + second + "::" + third

'a::b::guido'

In [28]:
"::".join(pieces)

'a::b::guido'

In [29]:
"guido" in val

True

In [31]:
val

'a,b,  guido'

In [30]:
val.index(",")

1

In [33]:
val.find(" ")

4

In [34]:
val.find(":")

-1

In [36]:
val.count(",")

2

In [37]:
val.replace(",", "::")

'a::b::  guido'

In [38]:
val.replace(",", "")

'ab  guido'

In [47]:
text = "foo    bar\t baz  \tqux"
print(text)

foo    bar	 baz  	qux


- `r"\s+"`: Jest to wyrażenie regularne, które oznacza “jeden lub więcej białych znaków”.

In [48]:
import re
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

- `re.split(pattern, string)`: Funkcja ta dzieli ciąg na podstawie wzorca podanego jako pierwszy argument. W tym przypadku wzorzec `r"\s+"` oznacza “jeden lub więcej białych znaków”.

In [49]:
text

'foo    bar\t baz  \tqux'

In [51]:
regex = re.compile(r"\s+")
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [52]:
regex.findall(text)

['    ', '\t ', '  \t']

In [53]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# Flaga re.IGNORECASE sprawia, że wyrażenie regularne nie zwraca uwagi na wielkość liter.
regex = re.compile(pattern, flags=re.IGNORECASE)

In [54]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [55]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [56]:
text[m.start():m.end()]

'dave@google.com'

In [57]:
print(regex.match(text))

None


- `repl`: Ciąg, który ma zastąpić dopasowane wzorce. W tym przypadku jest to `"REDACTED"`.

In [58]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [61]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex = re.compile(pattern, flags=re.IGNORECASE)
regex

re.compile(r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})',
re.IGNORECASE|re.UNICODE)

In [60]:
m = regex.match("wesm@bright.net")
m.groups()

('wesm', 'bright', 'net')

In [62]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

- Definicja: `regex.sub(repl, string)` przeszukuje ciąg `string` w poszukiwaniu wzorca `regex` i zastępuje go ciągiem `repl`, który może zawierać odniesienia do grup przechwytywania.

In [64]:
text

'Dave dave@google.com\nSteve steve@gmail.com\nRob rob@gmail.com\nRyan ryan@yahoo.com'

In [63]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


In [65]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}
data = pd.Series(data)
data
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [66]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [68]:
data_as_string_ext = data.astype('string')
print(data_as_string_ext)
data_as_string_ext.str.contains("gmail")

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string


Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [69]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

- `.str.findall(pattern, flags=re.IGNORECASE)`: Metoda ta przeszukuje każdy ciąg w serii `data`, aby znaleźć wszystkie wystąpienia wzorca `pattern`. Flaga `re.IGNORECASE` sprawia, że wyszukiwanie jest niewrażliwe na wielkość liter.

In [70]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]
matches
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [71]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [72]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [74]:
values = pd.Series(['apple', 'orange', 'apple',
                    'apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [75]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [76]:
pd.value_counts(values)

<ipython-input-76-e9d61bad5d62>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


apple     6
orange    2
Name: count, dtype: int64

In [77]:
values = pd.Series([0, 1, 0, 0] * 2)
dim = pd.Series(['apple', 'orange'])
print(values)
print(dim)

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64
0     apple
1    orange
dtype: object


- `dim.take(values)` zwraca nowy obiekt, który zawiera elementy wybrane na podstawie indeksów podanych w `values`.

In [78]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [79]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
N

8

- `np.random.default_rng()`: Funkcja ta tworzy nowy generator liczb losowych, który jest oparty na algorytmie `PCG64`. Jest to nowoczesny i bardziej wydajny sposób generowania liczb losowych w NumPy.

In [80]:
rng = np.random.default_rng(seed=12345)
rng

Generator(PCG64) at 0x7A4F3A637BC0

In [81]:
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [82]:
fruit_cat = df['fruit'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

- Jeśli `fruit_cat` jest obiektem typu `Categorical`, to `.array` zwraca wewnętrzną reprezentację tego obiektu jako tablicę. W przypadku obiektów kategorycznych, ta tablica będzie miała typ `CategoricalDtype`.

In [85]:
c = fruit_cat.array
print(c)
type(c)

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']
Categories (2, object): ['apple', 'orange']


pandas.core.arrays.categorical.Categorical

In [86]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [87]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [88]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

- `astype('category')`: Metoda `astype()` zmienia typ danych kolumny. W tym przypadku konwertuje kolumnę `fruit` na typ kategoryczny (`category`).
- Typ kategoryczny jest używany w Pandas do przechowywania danych, które mają ograniczoną liczbę unikalnych wartości (np. różne rodzaje owoców). Użycie tego typu może poprawić wydajność pamięci i przyspieszyć operacje analizy danych.

In [89]:
df['fruit'] = df['fruit'].astype('category')
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [90]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

- Funkcja `from_codes()` tworzy obiekt kategoryczny na podstawie podanych kodów i kategorii. Obiekt ten będzie zawierał wartości kategoryczne zdefiniowane przez listę `categories`, a ich wystąpienia będą określone przez listę `codes`.

In [91]:
categories = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]
my_cats_2 = pd.Categorical.from_codes(codes, categories)
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [92]:
ordered_cat = pd.Categorical.from_codes(codes, categories,
                                        ordered=True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [93]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [96]:
rng = np.random.default_rng(seed=12345)
draws = rng.standard_normal(1000)
draws[:5]

array([-1.4238,  1.2637, -0.8707, -0.2592, -0.0753])

- Funkcja `pd.qcut()` w Pandas jest używana do dzielenia danych na równe przedziały (kwantyle). W przypadku kodu `bins = pd.qcut(draws, 4)`, dane z tablicy `draws` są dzielone na cztery kwantyle. Oto szczegółowe wyjaśnienie działania tego kodu oraz jego zastosowania.

In [97]:
bins = pd.qcut(draws, 4)
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] <
                                           (0.687, 3.211]]

In [98]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
bins
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [99]:
bins = pd.Series(bins, name='quartile')
results = (pd.Series(draws)
           .groupby(bins)
           .agg(['count', 'min', 'max'])
           .reset_index())
results

<ipython-input-99-e24f63e0c221>:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(bins)


quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [100]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [101]:
N = 10_000_000
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [102]:
categories = labels.astype('category')

In [103]:
labels.memory_usage(deep=True)

600000128

In [104]:
categories.memory_usage(deep=True)

10000540

In [105]:
%time _ = labels.astype('category')

CPU times: user 569 ms, sys: 155 ms, total: 724 ms
Wall time: 722 ms


In [106]:
%timeit labels.value_counts()
%timeit categories.value_counts()

736 ms ± 215 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
45.1 ms ± 535 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [107]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)
cat_s = s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [109]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [110]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [111]:
actual_categories = ['a', 'b', 'c', 'd', 'e']
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [113]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [112]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

- Metoda `remove_unused_categories()` usuwa kategorie, które nie są używane w obiekcie kategorycznym. Po zastosowaniu tej metody, obiekt `cat_s3` będzie zawierał tylko te kategorie, które są rzeczywiście obecne w danych.

In [114]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]
cat_s3
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [115]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [116]:
pd.get_dummies(cat_s)

a      b      c      d
0   True  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4   True  False  False  False
5  False   True  False  False
6  False  False   True  False
7  False  False  False   True